# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Performance is a Feature!'
tagline:             ''
description:         ''
url:                 http://mattwarren.github.io
# Don't use baseurl, see https://talk.jekyllrb.com/t/what-trouble-happens-if-i-make-all-links-relative-instead-of-absolute/418/2
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Matt Warren
  url:               www.mattwarren.org
  email:             matt.warren@live.co.uk
  twitter:           matthewwarren
  twitterUrl:        https://twitter.com/matthewwarren
  github:            https://github.com/mattwarren/

# For the Jekyll SEO plugin https://github.com/jekyll/jekyll-seo-tag#usage
twitter:
  username: matthewwarren
  
# Custom vars
version:             1.0.0

exclude: [README.md, LICENSE.md]

# See http://milanaryal.com/2015/writing-on-github-pages-and-jekyll-using-markdown/
# and http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
# For tables see https://github.com/george-hawkins/basic-gfm-jekyll
# and https://george-hawkins.github.io/basic-gfm-jekyll/redcarpet-extensions.html

# https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
markdown: kramdown

highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#redcarpet:
#    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-paginate
  - rouge
  - jekyll-seo-tag